# fly.toml app configuration file generated for nendoroid-inventory on 2023-08-06T10:42:31-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nendoroid-inventory"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
